### ISSUE TITLE
Question / feature

### ISSUE THREAD

**Issue by azlux** [jelmer/ctrlproxy#1]
Hi,
I have one question about your project.
I'm looking for a short-time bouncer. I explain : I need a bouncer because my connection is not really good and i switch computer computer multiple time.
But I don't want to be connected all the time (even if it's in the away mode), because people think i'm still connected and continue to speak to me (and it's not funny when half of people are away because of bouncers). So the feature I need is : if not client are on the bouncer, it will disconnect to the irc servers after a timeout.
Do ctrlproxy will do that ?

Az

**Comment by jelmer** [comment]
On Thu, Jun 16, 2016 at 03:06:00AM -0700, azlux wrote:

> Hi,
> I have one question about your project.
> I'm looking for a short-time bouncer. I explain : I need a bouncer because my connection is not really good and i switch computer computer multiple time.
> But I don't want to be connected all the time (even if it's in the away mode), because people think i'm still connected and continue to speak to me (and it's not funny when half of people are away because of bouncers). So the feature I need is : if not client are on the bouncer, it will disconnect to the irc servers after a timeout.
> Do ctrlproxy will do that ?
> It's currently not supported but would be fairly easy to implement. In
> handle_client_disconnect, call disconnect_network(c->network) if
> c->network->clients is NULL.

Cheers,

Jelmer

**Comment by azlux** [comment]
great ! I will do like you say.
And what about a real implementation with an option into the conf file ? Do you think you will have time ? (I don't kown C , srry but i cannot help)
